# Generated by Django 6.0.5 on 2026-05-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='start_time',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('TEAM LEADER', 'Team Leader'), ('MEMBER', 'Member')], default='MEMBER', max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
    ]
