# Generated by Django 6.0.5 on 2026-05-25 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_rename_desription_project_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_role',
            unique_together={('user', 'project')},
        ),
    ]
