# Generated by Django 6.0.5 on 2026-08-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_invitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together=set(),
        ),
    ]
